Update wush-ng

diff --git a/src/wush-ng b/src/wush-ng
--- a/src/wush-ng
+++ b/src/wush-ng
@@ -11,29 +11,50 @@ function check_root(){
 }
 
 # function to choose the interface to be used.
-function choose_interface(){
-        clear
-        echo ""
-	echo "Available interfaces:"
-	echo ""
-    	available_interfaces=($(iw dev | awk '/Interface/{print $2}'))
-    	for ((c=0; c<"${#available_interfaces[@]}"; c++)); do
-    		echo "[${c}] ${available_interfaces[$c]}"
-   	done
-    	echo ""
+#!/bin/bash
 
-    	valid_interface=false
-    	while [[ "$valid_interface" = false ]]; do
-    		read -p "Please select the interface you want to use for the attack: " si
 
-        	if [[ "$si" -ge 0 ]] && [[ "$si" -lt "${#available_interfaces[@]}" ]]; then
-        		interface="${available_interfaces[$si]}"
-            		valid_interface=true
-         	else
-         		echo "Error: Interface not found. Please choose again."
-         	fi
-	done
-}          
+function choose_interface() {
+        interface_name=""
+        while [[ "$#" -gt 0 ]]; do
+                case "$1" in
+                    -i|--interface)
+                        if [[ -n "$2" ]]; then
+                            interface_name="$2"
+                            shift
+                        else
+                            echo "Error: Interface name not specified after -i or --interface."
+                            exit 1
+                        fi
+                        ;;
+                    *)
+                        echo "Error: Unrecognized option '$1'."
+                        exit 1
+                        ;;
+                esac
+                shift
+            done
+
+    if [[ -z "${interface_name}" ]]; then
+        echo "Error: Interface not specified. Use -i or --interface to specify the interface."
+        exit 1
+    fi
+
+    available_interfaces=($(iw dev | awk '/Interface/{print $2}'))
+    interface_found=false
+
+    for intf in "${available_interfaces[@]}"; do
+        if [[ "${intf}" == "${interface_name}" ]]; then
+            interface_found=true
+            break
+        fi
+    done
+
+    if [[ "${interface_found}" = false ]]; then
+        echo "Error: Interface '${interface_name}' not found."
+        exit 1
+    fi
+}
 
 function show_banner(){
         waktu=$(date +"%Y-%m-%d %H:%M:%S")
@@ -548,7 +569,7 @@ function exit_wush(){
 # wush-ng function
 function wush(){
 	check_root
-	choose_interface
+	choose_interface "$@"
 	show_banner
 	main
 }
